# Generated by Django 4.2 on 2025-03-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
